name: Notification horaire

on:
  schedule:
    - cron: '0 * * * *'   # toutes les heures
  workflow_dispatch:      # permet de lancer manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install requests

      - name: Exécuter le script
        run: python test_notify.py
